app/urls.py
from django.contrib import admin
from django.urls import path, include, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("workoutplan.urls")),
    path("", include("user.urls")),
    path("", include("shutdown.urls")),
    path("", include("weight.urls")),
]

weight/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('mass_input', views.mass_input, name='mass input'),
    path('mass_graph', views.mass_graph, name='mass graph')
]

weight_tracker/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

weight/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Mass(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,  
        on_delete=models.CASCADE,  
        related_name='mass'  
    )
    weight = models.FloatField(null=True, blank=True)
    fat = models.FloatField(null=True, blank=True)
    tbw = models.FloatField('Total Body Water', null=True, blank=True)
    bmi = models.FloatField('Body Mass Index', null=True, blank=True)
    muscle_mass = models.FloatField(null=True, blank=True)
    bone_density = models.FloatField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

weight/forms.py
from django import forms
from .models import Mass

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Mass
        fields = ['weight', 'fat', 'tbw', 'bmi', 'muscle_mass', 'bone_density']
        widgets = {
            'weight': forms.NumberInput(attrs={'step': 0.1, 'inputmode': 'float'}),
            'fat': forms.NumberInput(attrs={'step': 0.1, 'inputmode': 'float'}),
            'tbw': forms.NumberInput(attrs={'step': 0.1, 'inputmode': 'float'}),
            'bmi': forms.NumberInput(attrs={'step': 0.1, 'inputmode': 'float'}),
            'muscle_mass': forms.NumberInput(attrs={'step': 0.1, 'inputmode': 'float'}),
            'bone_density': forms.NumberInput(attrs={'step': 0.1, 'inputmode': 'float'}),
        }

weight/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test
import plotly.express as px
from .models import Mass
from .forms import UserProfileForm


# User Authenticated
def check_user_not_authenticated(user):
    return user.is_authenticated

@user_passes_test(check_user_not_authenticated, login_url='/login', redirect_field_name=None)
def mass_input(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            mass = form.save(commit=False)
            mass.user = request.user  
            mass.save()
            return redirect('plan')  
    else:
        form = UserProfileForm()
    return render(request, "mass_input.html", {'form': form})

@user_passes_test(check_user_not_authenticated, login_url='/login', redirect_field_name=None)
def mass_graph(request):
    user = request.user
    data = Mass.objects.filter(user=user).order_by('date_created')

    # Extracting data for the graph
    dates = [entry.date_created for entry in data]
    weights = [entry.weight for entry in data]

    # Creating the Plotly graph
    weight_chart = px.line(x=dates, y=weights, labels={'x': 'Date', 'y': 'Weight (kg)'}, title='Weight Over Time', template='plotly_dark')

    weight_chart_html = weight_chart.to_html(full_html=False)
    
    return render(request, 'mass_graph.html', {'weight_chart': weight_chart_html})

weight/templates/mass_graph.html
{% extends "base.html" %}

{% block title %}
Mass Graph
{% endblock %}

{% block content %}
<div>{{ weight_chart|safe }}</div>
{% endblock %}

weight/templates/mass_input.html
{% extends "base.html" %}

{% block title %}
Mass Input
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Enter Mass Below</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_weight">Weight (kg):</label>
            {{ form.weight }}
        </div>
        <div class="form-group">
            <label for="id_fat">Body Fat (%):</label>
            {{ form.fat }}
        </div>
        <div class="form-group">
            <label for="id_tbw">Total Body Water (TBW):</label>
            {{ form.tbw }}
        </div>
        <div class="form-group">
            <label for="id_bmi">Body Mass Index (BMI):</label>
            {{ form.bmi }}
        </div>
        <div class="form-group">
            <label for="id_muscle_mass">Muscle Mass (kg):</label>
            {{ form.muscle_mass }}
        </div>
        <div class="form-group">
            <label for="id_bone_density">Bone Density:</label>
            {{ form.bone_density }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

{% endblock %}